spring:
  application:
    name: basicboard
  datasource:
    url: jdbc:mysql://localhost:3306/basicboard?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mappers/*.xml
